export const routes = {
  login: "Login",
  signup: "Signup",
  termsAgreement: "TermsAgreement",
  signupComplete: "SignupComplete",
  home: "Home",
  customAlarm: "CustomAlarm",
  myPage: "MyPage",
  changePassword: "ChangePassword",
  findPassword: "FindPassword",
  notifications: "Notifications",
  accountInfo: "AccountInfo",
  notices: "Notices",
  noticeDetail: "NoticeDetail",
  faqs: "Faqs",
  privacyPolicy: "PrivacyPolicy",
  termsOfService: "TermsOfService",
  inquiry: "Inquiry",
  deleteAccount: "DeleteAccount",
};
